version: '2'
services:
  mdbus:
    restart: unless-stopped
    build: 
      context: ./mdbus
    privileged: true
    command: mbusd -L - -p /dev/ttyUSB0 -s 9600 -m 8N1  -d -v0
    ports:
      - 502:502
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0
  powermeter:
    restart: unless-stopped
    build:
      context: ./power-meter
    command: bash -c 'cd PowerMeter-Reader; while true; do python dataQuery.py; sleep 20; done'
    volumes:
      - ./settings.py:/PowerMeter-Reader/settings.py

  influxdb:
    restart: unless-stopped
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    restart: unless-stopped
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:

