version: '2'
services:
  mdbus:
    restart: unless-stopped
    build: 
      context: ./mdbus
    privileged: true
    command: mbusd -L - -p /dev/ttyUSB0 -s 9600 -m 8N1  -d -v9
    ports:
      - 502:502
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0
  powermeter:
    restart: unless-stopped
    build:
      context: ./power-meter
    command: bash -c 'cd PowerMeter-Reader; while true; do python main.py; sleep 20; done'
    volumes:
      - ./settings.py:/PowerMeter-Reader/settings.py

